version: "3.8"
services:
  application:
    build:
      context: .
    container_name: ics-threat-feeds-app
    expose:
      - "8080"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ics-threat-feeds-tunnel
    command: tunnel --url http://application:8080 --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - application
    restart: unless-stopped
