FROM python:3.13-alpine

# copy and setup requirements
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# install development tooling
RUN apk add --no-cache git
